### ISSUE TITLE
Change basemap

### ISSUE THREAD

**Issue by simgislab** [nextgis/metro4all-ios#12]
osm-mapnik for starters would be ok

**Comment by trolleway** [comment]
Does it possible to make a button for "выкачать кэш" of OSM tiles at medium zooms for city?

**Comment by simgislab** [comment]
Артём, ну не в тему же вопрос, не говоря уже о том, что это не приоритет и о том, что наборы тайлов если и должны готовиться, то на сервере, в пакете, а не на устройстве.
