### ISSUE TITLE
Отображение карты прилегающей территории для выбранной станции

### ISSUE THREAD

**Issue by marvin-yorke** [nextgis/metro4all-ios#2]
Выбор станции в алфавитном списке должен открывать экран с картой местности. Для начала возьмем стандартный MapKit, потом можно будет прикрутить кастомные тайлы

**Comment by simgislab** [comment]
на Android сейчас сделано так, выбор станции приводит к тому, что на этом же экране она раскрывается в перечень выходов, тут же, справа есть универсальная кнопка типа свойства, при нажатии на которую можно выбрать переход к карте или переход к схеме.

https://www.dropbox.com/s/q3st5ehzwd9i78a/Screenshot_2015-03-04-14-19-07.png

**Comment by marvin-yorke** [comment]
@simgislab это будет следующим шагом)
