### ISSUE TITLE
Старый логотип отображается при запуске приложения

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all-ios#20]
Между нажатием на иконку приложения и загрузкой экрана со списком станций на секунду появляется старый логотип - надо его убрать.

**Comment by marvin-yorke** [comment]
Сплэш нужен в любом случае, он отображается, пока система первый раз приложение загружает. Я взял это лого http://metro4all.org//img/logo.png с сайта, есть оно в векторе?

**Comment by Kinda-me** [comment]
Да, вот в векторе - https://www.dropbox.com/s/wi5mt9n81etasnd/%D0%A1hevronLogo.eps?dl=0
