### ISSUE TITLE
Показывать на карте выходы соседних станций

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all-ios#32]
Для станций, объединенных в пересадочный узел, актуальна ситуация, когда нужно видеть выходы со всех станций узла (например, выбрав станцию "Александровский сад", я не вижу выход с Боровицкой, это неудобно).

Чтобы решить эту проблему, нужно добавить на карту иконки соседних станций. Чтобы отличать их от иконок выбранной станции, можно сделать их полупрозрачными, как в андроид-приложении.

![screenshot_2015-03-28-23-14-00](https://cloud.githubusercontent.com/assets/6493848/6882718/47f7f0fa-d5a0-11e4-9773-22a119371029.png)

Варианты:
1) отображать полупрозрачными иконками выходы всех станций города, кроме выбранной (как в андроид-приложении). 
2) отображать полупрозрачными иконками выходы только с других станций узла, к которому относится станция.

**Comment by marvin-yorke** [comment]
Реализация мне конечно не очень нравится, но с таким форматом входных данных это наверно лучшее, что я могу сделать
