### ISSUE TITLE
Плашки в списке городов становятся уже после выбора города

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all-ios#33]
На iPhone 5C

![default](https://cloud.githubusercontent.com/assets/6493848/6893687/95c4f412-d6d7-11e4-9f2b-064ea4cdda17.jpg)

**Comment by marvin-yorke** [comment]
Нужно проверить на последней сборке. Я так и не воспроизвел у себя, но подоткнул фикс, который возможно должен это починить

**Comment by Kinda-me** [comment]
Вроде починилось, закрываю.
