### ISSUE TITLE
Падение при запуске

### ISSUE THREAD

**Issue by tugunov** [nextgis/metro4all-ios#37]
0.2 (29) при запуске падает, при этом потом его можно видеть в диспетчере приложений, но попытки открытия оттуда ни к чему не приводят. iPhone 4, iOS 7.1.2

**Comment by marvin-yorke** [comment]
Переустановка не помогает?

**Comment by tugunov** [comment]
Короче говоря, снес и установил сразу 0.2 (31). Запуск есть, загрузка данных для Москвы есть.

**Comment by marvin-yorke** [comment]
Тогда все ок, на промежуточных сборках это нормально
