### ISSUE TITLE
Строка поиска 

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all-ios#38]
1. "Прибить" ее к заголовку, чтобы она не скрывалась при проматывании списка станций вниз.
2. Локализовать плейсхолдер и кнопку отмены (сейчас Search и Cancel).

**Comment by marvin-yorke** [comment]
> "Прибить" ее к заголовку, чтобы она не скрывалась при проматывании списка станций вниз
> Не уверен, что это возможно. Посмотрю
