### ISSUE TITLE
Сверять данные из кэша с meta.json

### ISSUE THREAD

**Issue by marvin-yorke** [nextgis/metro4all-ios#4]
Если есть закэшированные данные и их версия совпадает с meta, не загружать данные заново

**Comment by marvin-yorke** [comment]
Проверка версии наверно пойдет отдельным пунктом, мы же не загружаем принудительно новые данные? Уведомляем пользователя, но пользуемся старыми, пока он не запросит обновление? 

Сохранение данных в кэш и загрузку их оттуда сделал

**Comment by simgislab** [comment]
да, принудительно не загружаем, по крайней мере пока
