### ISSUE TITLE
Добавить возможность принудительного обновления данных по загруженным городам

### ISSUE THREAD

**Issue by Kinda-me** [nextgis/metro4all-ios#47]

**Comment by marvin-yorke** [comment]
она есть. Нужно выбрать город из "Доступных", а не "на устройстве". Тогда при наличии более новой версии он ее скачает. "На устройтве" - не проверяет на сервере, просто открывает то, что загружено. Нужно прикрутить индикацию наличия новой версии в "Доступных"

**Comment by Kinda-me** [comment]
Тут скорее другой кейс: форс-апдейт нужен, если при загрузке последней версии данных происходит какой-то сбой, в результате которого приложение считает, что у него есть данные последней версии, а по факту там какой-то косяк, и надо перезагрузить ту же версию данных.
Возможно, если будет возможность удалить текущую версию данных и скачать их по новой, это не так актуально.

**Comment by marvin-yorke** [comment]
Такое надо в принципе предотвращать :) Удаление я сделаю, а пока подумаем
