### ISSUE TITLE
Натянуть дизайн

### ISSUE THREAD

**Issue by marvin-yorke** [nextgis/metro4all-ios#6]

**Comment by marvin-yorke** [comment]
Добавил сплэш-скрин, будет здорово, если пришлете лого в векторе. Пока взял с сайта, но оно плохо тянется
https://github.com/nextgis/metro4all-ios/blob/master/metro4all-ios/Images.xcassets/LaunchImage.launchimage/35in.png

**Comment by Kinda-me** [comment]
Лого в векторе вот - https://github.com/nextgis/metro4all/blob/master/art/v2/appIcon.svg
